export const dataBase = [
	{
		id:0,
		theme: 'lesProphetes',
		niveau: "1",
		private: false,
		question: 'Quel est le Prophète le plus cité dans le coran ?',
		choix: ['Issa ﷺ', 'Moussa ﷺ', 'Ibrahim ﷺ', 'Mohammed ﷺ'],
		reponse: "1",
		info: 'Moussa ﷺ est cité 136 fois',
	},
	{
		id:1,
		theme: 'coran',
		niveau: "1",
		private: false,
		question: 'Combien y-a-t-il de mois sacrés dans le calendrier islamique ?',
		choix: ["1", "2", "4", "6"],
		reponse: "2",
		info: '',
	},
	{
		id:2,
		theme: 'coran',
		niveau: "3",
		private: false,
		question: 'Quels sont les mois sacrés ?',
		choix: [
			'Ramadan, Dhul Hijah, Safar et Chawwal',
			'Ramadan, Chaabane, Dhul Hijjah et Safar',
			"Dhul Hijjah, Radjab, Mouharram et Dhul Qi'dah",
			'Mouharram, Ramadan, Dhul Hijjah et Chawwal',
		],
		reponse: "2",
		info: "Ramadan n'est pas un mois sacré",
	},
	{
		id:3,
		theme: 'coran',
		niveau: "2",
		private: false,
		question:
			'Quelle est la seule sourate qui ne commence pas par la formule de « Basmala » ?',
		choix: ['Al Baqarah', 'AtTawba', 'Ya Sin', 'Al Moulk'],
		reponse: "1",
		info: "Certains savants disent qu'elle est la suite de la sourate Al Anfal",
	},
	{
		id:4,
		theme: 'prophete',
		niveau: "2",
		private: false,
		question: 'Comment s’appelle le peuple qui a accueilli le prophète ﷺ à Médine ?',
		choix: ['Quraych', 'Ansars', 'Banu Nadir', 'Banu Ghatafan'],
		reponse: "1",
		info: 'Ansar signifie les auxiliaires',
	},
	{
		id:5,
		theme: 'coran',
		niveau: "1",
		private: false,
		question: 'Les anges sont faits',
		choix: ["D'argile", 'De feu', 'De fumée', 'De lumière'],
		reponse: "3",
		info: '',
	},
	{
		id:6,
		theme: 'prophete',
		niveau: "3",
		private: false,
		question: "Quel est le meilleure don qu'Allah a offert à l’Homme ?",
		choix: ["L'amour", 'La patience', 'La force', 'La pudeur'],
		reponse: "1",
		info:
			'Celui qui persévère Allah lui donne la patience. Aucun homme n’a reçu de meilleur don que la patience (Boukhari)',
	},
	{
		id:7,
		theme: 'coran',
		niveau: "2",
		private: false,
		question: 'Laquelle de ces sourates ne débute pas par des lettres détachées?',
		choix: ['Maryam', 'Luqman', 'Taha', 'Al furkan'],
		reponse: "3",
		info: '29 sourates debutent par des lettres détachées',
	},
	{
		id:8,
		theme: 'coran',
		niveau: "2",
		private: false,
		question: 'Quel est le seul compagnon dont le nom est cité dans le Coran ?',
		choix: ['Zayd', 'Ali', 'Omar', 'Abu Bakr'],
		reponse: "0",
		info: 'Zayd fut le fils adoptif du Prophète ﷺ',
	},
	{
		id:9,
		theme: 'coran',
		niveau: "1",
		private: false,
		question: 'Lesquel de ces animaux n’ont pas de sourate à leur nom ?',
		choix: ['Les fourmis', 'Les abeilles', "L'araignée", 'La balaine'],
		reponse: "3",
		info:
			"5 sourates portent des noms d'animaux: la vache, l'éléphant,les fourmis, les abeilles, l'araignée",
	},
	{
		id:10,
		theme: 'histoire',
		niveau: "1",
		private: false,
		question: 'Qui fut le 4ème Calife ?',
		choix: ['Ali', 'Omar', 'Othman', 'Abu Bakr'],
		reponse: "3",
		info: '',
	},
];
